version: '3.3'
services:
  sql-service:
    build:
      context: .
      dockerfile: Dockerfile 
    image: sql-service
    restart: unless-stopped
    depends_on: 
     - db
    stdin_open: true
    tty: true
    volumes:
      - ./results:/results
    networks:
      - db-network
  db:
    image: linuxserver/mariadb:latest
    container_name: db
    restart : always
#    ports:
#         - "3306:3306"
    environment:
        - PUID=1000
        - PGID=1000
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=user
        - MYSQL_PASSWORD=root
    volumes:
         - ./mariadb-data:/config
    networks: 
      db-network:
        aliases:
          - db

networks: 
  db-network:
