version: '3.3'
services:
  sql_service:
    build:
      context: .
      dockerfile: Dockerfile 
    image: sql_service
    restart: unless-stopped
    depends_on: 
     - db
    stdin_open: true
    networks:
      - db-network
  db:
    image: mariadb:10.4
    restart : always
    ports:
         - "3306:3306"
    environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_USER=user
         - MYSQL_PASSWORD=root
         - MYSQL_DATABASE=baseball
    volumes:
         - mariadb-data:/var/lib/mysql
    networks: 
      db-network:
        aliases:
          - db

networks: 
  db-network:
    

volumes:
  mariadb-data:
 

